/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type { Concentration, Major, Minor } from "./northStarAPI.schemas";

import { customAxios } from "./apiClient";

export const getAcademic = () => {
  /**
   * Returns a list of all available majors.
   * @summary Get all majors
   */
  const getAcademicMajors = () => {
    return customAxios<Major[]>({ url: `/academic/majors`, method: "GET" });
  };
  /**
   * Returns a list of all available concentrations.
   * @summary Get all concentrations
   */
  const getAcademicConcentrations = () => {
    return customAxios<Concentration[]>({ url: `/academic/concentrations`, method: "GET" });
  };
  /**
   * Returns a list of all available minors.
   * @summary Get all minors
   */
  const getAcademicMinors = () => {
    return customAxios<Minor[]>({ url: `/academic/minors`, method: "GET" });
  };
  return { getAcademicMajors, getAcademicConcentrations, getAcademicMinors };
};
export type GetAcademicMajorsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAcademic>["getAcademicMajors"]>>
>;
export type GetAcademicConcentrationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAcademic>["getAcademicConcentrations"]>>
>;
export type GetAcademicMinorsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAcademic>["getAcademicMinors"]>>
>;
