/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type { AiSummary, GetAiSummariesPopularParams } from "./northStarAPI.schemas";

import { customAxios } from "./apiClient";

export const getAiSummary = () => {
  /**
   * Returns the top most popular course and professor reviews ranked by a popularity score.
   * @summary Get popular conversations with AI summaries
   */
  const getAiSummariesPopular = (params?: GetAiSummariesPopularParams) => {
    return customAxios<AiSummary[]>({ url: `/ai-summaries/popular`, method: "GET", params });
  };
  return { getAiSummariesPopular };
};
export type GetAiSummariesPopularResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAiSummary>["getAiSummariesPopular"]>>
>;
