/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAuthCallbackParams,
  Student
} from './northStarAPI.schemas';

import { customAxios } from './apiClient';




  export const getAuth = () => {
/**
 * Redirects the user to Google's OAuth consent screen for authentication
 * @summary Login Feature with Google
 */
const getAuthLogin = (
    
 ) => {
      return customAxios<unknown>(
      {url: `/auth/login`, method: 'GET'
    },
      );
    }
  /**
 * Redirects the user to Google's OAuth consent screen for authentication
 * @summary Login Feature with Google
 */
const getAuthSignup = (
    
 ) => {
      return customAxios<unknown>(
      {url: `/auth/signup`, method: 'GET'
    },
      );
    }
  /**
 * Handles redirect from Google after authentication, validating Northeastern email, and creating or finding student
 * @summary Google OAuth callback
 */
const getAuthCallback = (
    params: GetAuthCallbackParams,
 ) => {
      return customAxios<Student>(
      {url: `/auth/callback`, method: 'GET',
        params
    },
      );
    }
  return {getAuthLogin,getAuthSignup,getAuthCallback}};
export type GetAuthLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['getAuthLogin']>>>
export type GetAuthSignupResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['getAuthSignup']>>>
export type GetAuthCallbackResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['getAuthCallback']>>>
