/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Forge S26 Project API
 * OpenAPI spec version: 0.1.0
 */
export type ErrorMessageAnyOf = { [key: string]: unknown };

/**
 * Error message or validation errors
 */
export type ErrorMessage = string | ErrorMessageAnyOf;

export interface Error {
  /** HTTP status code */
  code: number;
  /** Error message or validation errors */
  message: ErrorMessage;
}

export interface Sample {
  /** The ID of the sample retrieved */
  id: string;
  /** The name of the sample */
  name: string;
  created_at: string;
  updated_at: string;
}

export type ProfessorTagsItem = typeof ProfessorTagsItem[keyof typeof ProfessorTagsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessorTagsItem = {
  boston: 'boston',
  oakland: 'oakland',
  london: 'london',
} as const;

export interface Professor {
  /** the unique id of the professor */
  id: string;
  /** the first name of the professor */
  firstName: string;
  /** the last name of the professor */
  lastName: string;
  /**
   * location tags for the professor
   * @nullable
   */
  tags?: ProfessorTagsItem[] | null;
  createdAt: string;
  updatedAt: string;
}

export type ProfessorPostInputTagsItem = typeof ProfessorPostInputTagsItem[keyof typeof ProfessorPostInputTagsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessorPostInputTagsItem = {
  boston: 'boston',
  oakland: 'oakland',
  london: 'london',
} as const;

export interface ProfessorPostInput {
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /** @nullable */
  tags?: ProfessorPostInputTagsItem[] | null;
}

export type ProfessorPatchInputTagsItem = typeof ProfessorPatchInputTagsItem[keyof typeof ProfessorPatchInputTagsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessorPatchInputTagsItem = {
  boston: 'boston',
  oakland: 'oakland',
  london: 'london',
} as const;

export interface ProfessorPatchInput {
  /** @minLength 1 */
  firstName?: string;
  /** @minLength 1 */
  lastName?: string;
  /** @nullable */
  tags?: ProfessorPatchInputTagsItem[] | null;
}

