/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Forge S26 Project API
 * OpenAPI spec version: 0.1.0
 */
import { customAxios } from './apiClient';




  export const getHealth = () => {
/**
 * Check if the API is running and healthy
 * @summary Health check
 */
const getHealth = (
    
 ) => {
      return customAxios<void>(
      {url: `/health`, method: 'GET'
    },
      );
    }
  return {getHealth}};
export type GetHealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHealth>['getHealth']>>>
