/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
export type UuidParam = string;

export type ErrorMessageAnyOf = { [key: string]: unknown };

/**
 * Error message or validation errors
 */
export type ErrorMessage = string | ErrorMessageAnyOf;

export interface Error {
  /** HTTP status code */
  code: number;
  /** Error message or validation errors */
  message: ErrorMessage;
}

export type BadRequestError = Error;

export type InternalServerError = Error;

export interface Sample {
  /** The ID of the sample retrieved */
  id: string;
  /** The name of the sample */
  name: string;
  created_at: string;
  updated_at: string;
}

export interface CourseThread {
  id: UuidParam;
  studentId: UuidParam;
  courseReviewId: UuidParam;
  /** @maxLength 2000 */
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface CourseThreadPostInput {
  studentId: UuidParam;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}

export interface CourseThreadPatchInput {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}

export type GetCourseReviewsIdThreadsParams = {
/**
 * Page number of pagination
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page in pagination
 * @minimum 1
 */
limit?: number;
};

export type GetSamplesParams = {
/**
 * Page number of pagination
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page in pagination
 * @minimum 1
 */
limit?: number;
};

