/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
export type UuidParam = string;

/**
 * Error message or validation errors
 */
export type ErrorMessage = string | { [key: string]: unknown };

export interface Error {
  /** HTTP status code */
  code: number;
  /** Error message or validation errors */
  message: ErrorMessage;
}

export type BadRequestError = Error;

export type InternalServerError = Error;

export interface Sample {
  /** The ID of the sample retrieved */
  id: string;
  /** The name of the sample */
  name: string;
  created_at: string;
  updated_at: string;
}

/**
 * The department offering the course
 */
export type CourseDepartment = {
  /** The ID of the department offering the course */
  id: number;
  /** The name of the department offering the course */
  name: string;
};

/**
 * The type of lecture format for the course
 */
export type CourseLectureType = (typeof CourseLectureType)[keyof typeof CourseLectureType] | null;

export const CourseLectureType = {
  lecture: "lecture",
  lab: "lab",
  online: "online",
} as const;

export interface Course {
  /** The ID of the course retrieved */
  id: string;
  /** The name of the course */
  name: string;
  /** The department offering the course */
  department: CourseDepartment;
  /** The identifying code for the course within the department */
  course_code: number;
  /** A brief description of the course content and objectives */
  description: string;
  /** The number of credits awarded for completing the course */
  num_credits: number;
  /** The type of lecture format for the course */
  lecture_type?: CourseLectureType;
  created_at: string;
  updated_at: string;
}

/**
 * The type of lecture format for the course
 */
export type CoursePostInputLectureType =
    | (typeof CoursePostInputLectureType)[keyof typeof CoursePostInputLectureType]
    | null;

export const CoursePostInputLectureType = {
  lecture: "lecture",
  lab: "lab",
  online: "online",
} as const;

export interface CoursePostInput {
  /** The name of the course to be created */
  name: string;
  /** The ID of the department offering the course */
  department_id: number;
  /**
   * The identifying code for the course within the department
   * @minimum 1000
   * @maximum 10000
   */
  course_code: number;
  /** A brief description of the course content and objectives */
  description: string;
  /**
   * The number of credits awarded for completing the course
   * @minimum 1
   * @maximum 6
   */
  num_credits: number;
  /** The type of lecture format for the course */
  lecture_type?: CoursePostInputLectureType;
}

/**
 * The type of lecture format for the course
 */
export type CoursePatchInputLectureType =
    (typeof CoursePatchInputLectureType)[keyof typeof CoursePatchInputLectureType];

export const CoursePatchInputLectureType = {
  lecture: "lecture",
  lab: "lab",
  online: "online",
} as const;

export interface CoursePatchInput {
  /** The name of the course to be created */
  name?: string;
  /** The ID of the department offering the course */
  department_id?: number;
  /**
   * The identifying code for the course within the department
   * @minimum 1000
   * @maximum 10000
   */
  course_code?: number;
  /** A brief description of the course content and objectives */
  description?: string;
  /**
   * The number of credits awarded for completing the course
   * @minimum 1
   * @maximum 6
   */
  num_credits?: number;
  /** The type of lecture format for the course */
  lecture_type?: CoursePatchInputLectureType;
}

export interface CourseThread {
  id: UuidParam;
  studentId: UuidParam;
  courseReviewId: UuidParam;
  /** @maxLength 2000 */
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface CourseThreadPostInput {
  studentId: UuidParam;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}

export interface CourseThreadPatchInput {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}

export interface SamplePostInput {
  /** @minLength 1 */
  name: string;
}

export interface SamplePatchInput {
  /** @minLength 1 */
  name?: string;
  updated_at?: string;
}

export type ProfessorTagsItem = (typeof ProfessorTagsItem)[keyof typeof ProfessorTagsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessorTagsItem = {
  boston: "boston",
  oakland: "oakland",
  london: "london",
} as const;

export interface Professor {
  /** the unique id of the professor */
  id: string;
  /** the first name of the professor */
  firstName: string;
  /** the last name of the professor */
  lastName: string;
  /**
   * location tags for the professor
   * @nullable
   */
  tags?: ProfessorTagsItem[] | null;
  createdAt: string;
  updatedAt: string;
}


export type ProfessorPostInputTagsItem =
    (typeof ProfessorPostInputTagsItem)[keyof typeof ProfessorPostInputTagsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessorPostInputTagsItem = {
  boston: "boston",
  oakland: "oakland",
  london: "london",
} as const;

export interface ProfessorPostInput {
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /** @nullable */
  tags?: ProfessorPostInputTagsItem[] | null;
}

export interface ProfessorPatchInput {
  /** @minLength 1 */
  firstName?: string;
  /** @minLength 1 */
  lastName?: string;
  /** @nullable */
  tags?: ProfessorPostInputTagsItem[] | null;
}

export interface BaseReview {
  /** The unique ID of the review */
  id: string;
  /** The ID of the student who wrote the review (null if anonymous) */
  studentId?: string | null;
  /**
   * Rating from 1 (worst) to 5 (best)
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
  /**
   * The review content (profanity is censored automatically)
   * @minLength 1
   * @maxLength 2000
   */
  reviewText?: string;
  /** Optional tags attached to the review */
  tags?: string[] | null;
  createdAt: string;
  updatedAt: string;
}

export type CourseReview = BaseReview & {
  /** The ID of the course being reviewed */
  courseId: string;
};

export type ProfessorReview = BaseReview & {
  /** The ID of the professor being reviewed */
  professorId: string;
};

export type Review = CourseReview | ProfessorReview;

export interface ReviewPostInput {
  /** The ID of the student submitting the review (omit for anonymous) */
  studentId?: string | null;
  /**
   * Rating from 1 (worst) to 5 (best)
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /**
   * The review content
   * @minLength 1
   * @maxLength 2000
   */
  reviewText: string;
  /** The ID of the course to review (mutually exclusive with professorId) */
  courseId?: string | null;
  /** The ID of the professor to review (mutually exclusive with courseId) */
  professorId?: string | null;
  /** Optional tags for the review */
  tags?: string[];
}

export interface ReviewPatchInput {
  /**
   * Updated rating
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
  /**
   * Updated review content (profanity will be censored)
   * @minLength 1
   * @maxLength 2000
   */
  reviewText?: string;
  /** Updated tags (null clears all tags) */
  tags?: string[] | null;
}

export interface ProfThread {
  id?: UuidParam;
  studentId?: UuidParam;
  profReviewId?: UuidParam;
  /** @maxLength 2000 */
  content?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ProfThreadPostInput {
  studentId: UuidParam;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}

export interface ProfThreadPatchInput {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content?: string;
}

export type GetCourseReviewsIdThreadsParams = {
  /**
   * Page number of pagination
   * @minimum 1
   */
  page?: number;
  /**
   * Number of items per page in pagination
   * @minimum 1
   */
  limit?: number;
};

export type GetProfessorReviewsIdThreadsParams = {
  /**
   * Page number of pagination
   * @minimum 1
   */
  page?: number;
  /**
   * Number of items per page in pagination
   * @minimum 1
   */
  limit?: number;
};

export type GetSamplesParams = {
  /**
   * Page number of pagination
   * @minimum 1
   */
  page?: number;
  /**
   * Number of items per page in pagination
   * @minimum 1
   */
  limit?: number;
};

export type GetCoursesParams = {
  /**
   * Page number of pagination
   * @minimum 1
   */
  page?: number;
  /**
   * Number of items per page in pagination
   * @minimum 1
   */
  limit?: number;
};

export type GetReviewsParams = {
  /**
   * Number of items to return (1–100)
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Number of items to skip
   * @minimum 0
   */
  offset?: number;
};

export type GetProfessorsParams = {
  /**
   * Page number of pagination
   * @minimum 1
   */
  page?: number;
  /**
   * Number of items per page in pagination
   * @minimum 1
   */
  limit?: number;
};

export type GetAuthCallbackParams = {
  /**
   * Authorization code from Google OAuth 2.0
   */
  code: string;
};

export type GetAuthCallback200 = {
  message?: string;
  /** JWT access token */
  token?: string;
};

export type GetAuthCallback201 = {
  message?: string;
  /** JWT access token */
  token?: string;
};