/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
export type ErrorMessageAnyOf = { [key: string]: unknown };

/**
 * Error message or validation errors
 */
export type ErrorMessage = string | ErrorMessageAnyOf;

export interface Error {
  /** HTTP status code */
  code: number;
  /** Error message or validation errors */
  message: ErrorMessage;
}

export interface Sample {
  /** The ID of the sample retrieved */
  id: string;
  /** The name of the sample */
  name: string;
  created_at: string;
}

