/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetProfessorsParams,
  Professor,
  ProfessorPatchInput,
  ProfessorPostInput,
  Rmp
} from './northStarAPI.schemas';

import { customAxios } from './apiClient';

export const getProfessor = () => {
  const getProfessors = (params?: GetProfessorsParams) => {
    return customAxios<Professor[]>({ url: `/professors`, method: "GET", params });
  };
  const postProfessors = (professorPostInput: ProfessorPostInput) => {
    return customAxios<Professor>({
      url: `/professors`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: professorPostInput,
    });
  };
  const getProfessorsId = (id: string) => {
    return customAxios<Professor>({ url: `/professors/${id}`, method: "GET" });
  };
  const patchProfessorsId = (id: string, professorPatchInput: ProfessorPatchInput) => {
    return customAxios<Professor>({
      url: `/professors/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: professorPatchInput,
    });
  };
  const deleteProfessorsId = (id: string) => {
    return customAxios<void>({ url: `/professors/${id}`, method: "DELETE" });
  };
  const getProfessorsIdRmp = (id: string) => {
    return customAxios<Rmp>({ url: `/professors/${id}/rmp`, method: "GET" });
  };
  const postRmp = () => {
    return customAxios<Rmp>({ url: `/rmp`, method: "POST" });
  };
  return { getProfessors, postProfessors, getProfessorsId, patchProfessorsId, deleteProfessorsId, getProfessorsIdRmp, postRmp };
};
export type GetProfessorsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>["getProfessors"]>>>;
export type PostProfessorsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>["postProfessors"]>>>;
export type GetProfessorsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>["getProfessorsId"]>>>;
export type PatchProfessorsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>["patchProfessorsId"]>>>;
export type DeleteProfessorsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>["deleteProfessorsId"]>>>;
export type GetProfessorsIdRmpResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>["getProfessorsIdRmp"]>>>;
export type PostRmpResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>["postRmp"]>>>;