/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetProfessorsParams,
  Professor,
  ProfessorPatchInput,
  ProfessorPostInput,
  Rmp
} from './northStarAPI.schemas';

import { customAxios } from './apiClient';




  export const getProfessor = () => {
/**
 * Returns a list of all professors
 * @summary Get all professors
 */
const getProfessors = (
    params?: GetProfessorsParams,
 ) => {
      return customAxios<Professor[]>(
      {url: `/professors`, method: 'GET',
        params
    },
      );
    }
  /**
 * Creates a new professor
 * @summary Create a professor
 */
const postProfessors = (
    professorPostInput: ProfessorPostInput,
 ) => {
      return customAxios<Professor>(
      {url: `/professors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: professorPostInput
    },
      );
    }
  /**
 * Returns a single professor by their UUID
 * @summary Get professor by ID
 */
const getProfessorsId = (
    id: string,
 ) => {
      return customAxios<Professor>(
      {url: `/professors/${id}`, method: 'GET'
    },
      );
    }
  /**
 * Partially updates a professor by their UUID
 * @summary Update a professor
 */
const patchProfessorsId = (
    id: string,
    professorPatchInput: ProfessorPatchInput,
 ) => {
      return customAxios<Professor>(
      {url: `/professors/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: professorPatchInput
    },
      );
    }
  /**
 * Deletes a professor by their UUID
 * @summary Delete a professor
 */
const deleteProfessorsId = (
    id: string,
 ) => {
      return customAxios<void>(
      {url: `/professors/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * Returns the Rate My Professor data stored in our DB for a given professor
 * @summary Get RMP data for a professor
 */
const getProfessorsIdRmp = (
    id: string,
 ) => {
      return customAxios<Rmp>(
      {url: `/professors/${id}/rmp`, method: 'GET'
    },
      );
    }
  /**
 * Pings the external RMP API, matches data to professors in our DB, and bulk inserts
 * @summary Fetch and save RMP data for all professors
 */
const postRmp = (
    
 ) => {
      return customAxios<Rmp>(
      {url: `/rmp`, method: 'POST'
    },
      );
    }
  return {getProfessors,postProfessors,getProfessorsId,patchProfessorsId,deleteProfessorsId,getProfessorsIdRmp,postRmp}};
export type GetProfessorsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>['getProfessors']>>>
export type PostProfessorsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>['postProfessors']>>>
export type GetProfessorsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>['getProfessorsId']>>>
export type PatchProfessorsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>['patchProfessorsId']>>>
export type DeleteProfessorsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>['deleteProfessorsId']>>>
export type GetProfessorsIdRmpResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>['getProfessorsIdRmp']>>>
export type PostRmpResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfessor>['postRmp']>>>
