/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetReviewsParams,
  Review,
  ReviewPatchInput,
  ReviewPostInput,
  UuidParam,
} from "./northStarAPI.schemas";

import { customAxios } from "./apiClient";

export const getReview = () => {
  /**
   * Returns a paginated list of all course and professor reviews.
   * @summary Get all reviews
   */
  const getReviews = (params?: GetReviewsParams) => {
    return customAxios<Review[]>({ url: `/reviews`, method: "GET", params });
  };
  /**
 * Creates a new course or professor review.
Exactly one of `courseId` or `professorId` must be provided.

 * @summary Create a review
 */
  const postReviews = (reviewPostInput: ReviewPostInput) => {
    return customAxios<Review>({
      url: `/reviews`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: reviewPostInput,
    });
  };
  /**
   * Returns a single course or professor review by its UUID.
   * @summary Get review by ID
   */
  const getReviewsId = (id: UuidParam) => {
    return customAxios<Review>({ url: `/reviews/${id}`, method: "GET" });
  };
  /**
   * Partially updates an existing review. Review text is automatically censored for profanity.
   * @summary Update a review
   */
  const patchReviewsId = (id: UuidParam, reviewPatchInput: ReviewPatchInput) => {
    return customAxios<Review>({
      url: `/reviews/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: reviewPatchInput,
    });
  };
  /**
   * Deletes a review by its UUID.
   * @summary Delete a review
   */
  const deleteReviewsId = (id: UuidParam) => {
    return customAxios<void>({ url: `/reviews/${id}`, method: "DELETE" });
  };
  return { getReviews, postReviews, getReviewsId, patchReviewsId, deleteReviewsId };
};
export type GetReviewsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReview>["getReviews"]>>
>;
export type PostReviewsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReview>["postReviews"]>>
>;
export type GetReviewsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReview>["getReviewsId"]>>
>;
export type PatchReviewsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReview>["patchReviewsId"]>>
>;
export type DeleteReviewsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReview>["deleteReviewsId"]>>
>;
