/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetSamplesParams,
  Sample,
  SamplePatchInput,
  SamplePostInput,
} from "./northStarAPI.schemas";

import { customAxios } from "./apiClient";

export const getSample = () => {
  /**
   * This endpoint gets all samples that we have
   * @summary Getting Samples
   */
  const getSamples = (params?: GetSamplesParams) => {
    return customAxios<Sample[]>({ url: `/samples`, method: "GET", params });
  };
  /**
   * This endpoint creates a new sample with the provided details
   * @summary Create a New Sample
   */
  const postSamples = (samplePostInput: SamplePostInput) => {
    return customAxios<Sample>({
      url: `/samples`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: samplePostInput,
    });
  };
  /**
   * This endpoint retrieves a specific sample by its ID
   * @summary Get Sample by ID
   */
  const getSamplesId = (id: string) => {
    return customAxios<Sample>({ url: `/samples/${id}`, method: "GET" });
  };
  /**
   * This endpoint updates the details of a specific sample by its ID
   * @summary Update Sample by ID
   */
  const patchSamplesId = (id: string, samplePatchInput: SamplePatchInput) => {
    return customAxios<Sample>({
      url: `/samples/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: samplePatchInput,
    });
  };
  /**
   * This endpoint deletes a specific sample by its ID
   * @summary Delete Sample by ID
   */
  const deleteSamplesId = (id: string) => {
    return customAxios<void>({ url: `/samples/${id}`, method: "DELETE" });
  };
  return { getSamples, postSamples, getSamplesId, patchSamplesId, deleteSamplesId };
};
export type GetSamplesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSample>["getSamples"]>>
>;
export type PostSamplesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSample>["postSamples"]>>
>;
export type GetSamplesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSample>["getSamplesId"]>>
>;
export type PatchSamplesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSample>["patchSamplesId"]>>
>;
export type DeleteSamplesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSample>["deleteSamplesId"]>>
>;
