/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetSamplesParams,
  Sample
} from './northStarAPI.schemas';

import { customAxios } from './apiClient';




  export const getSample = () => {
/**
 * This endpoint gets all samples that we have
 * @summary Getting Samples
 */
const getSamples = (
    params?: GetSamplesParams,
 ) => {
      return customAxios<Sample>(
      {url: `/samples`, method: 'GET',
        params
    },
      );
    }
  return {getSamples}};
export type GetSamplesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSample>['getSamples']>>>
