/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetStudentsParams,
  PatchStudentsIdBodyOne,
  Student,
  StudentConcentrationPostInput,
  StudentMajorPostInput,
  StudentMinorPostInput,
  StudentPatchInput,
  StudentPostInput,
} from "./northStarAPI.schemas";

import { customAxios } from "./apiClient";

export const getStudent = () => {
  /**
   * Returns a list of all students with ID, first name, last name, email, graduation year, and preferences.
   * @summary Get all students
   */
  const getStudents = (params?: GetStudentsParams) => {
    return customAxios<Student[]>({ url: `/students`, method: "GET", params });
  };
  /**
   * Create a new student with the provided information.
   * @summary Create a student
   */
  const postStudents = (studentPostInput: StudentPostInput) => {
    return customAxios<Student>({
      url: `/students`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: studentPostInput,
    });
  };
  /**
   * Returns a single student by their unique email-ID.
   * @summary Get student by their Email
   */
  const getStudentsEmailEmail = (email: string) => {
    return customAxios<Student>({ url: `/students/email/${email}`, method: "GET" });
  };
  /**
   * Returns a single student by their UUID.
   * @summary Get student by ID
   */
  const getStudentsId = (id: string) => {
    return customAxios<Student>({ url: `/students/${id}`, method: "GET" });
  };
  /**
   * Update a student's information using their UUID. Supports optional profile picture upload via multipart/form-data.
   * @summary Update a student
   */
  const patchStudentsId = (
    id: string,
    patchStudentsIdBody: PatchStudentsIdBodyOne | StudentPatchInput,
  ) => {
    return customAxios<Student>({
      url: `/students/${id}`,
      method: "PATCH",
      data: patchStudentsIdBody,
    });
  };
  /**
   * Deletes a student by their UUID.
   * @summary Delete a student
   */
  const deleteStudentsId = (id: string) => {
    return customAxios<void>({ url: `/students/${id}`, method: "DELETE" });
  };
  /**
   * Associates a major with the specified student.
   * @summary Add a major to a student
   */
  const postStudentsIdMajors = (id: string, studentMajorPostInput: StudentMajorPostInput) => {
    return customAxios<void>({
      url: `/students/${id}/majors`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: studentMajorPostInput,
    });
  };
  /**
   * Removes the association between a student and a major.
   * @summary Remove a major from a student
   */
  const deleteStudentsIdMajorsMajorId = (id: string, majorId: number) => {
    return customAxios<void>({ url: `/students/${id}/majors/${majorId}`, method: "DELETE" });
  };
  /**
   * Associates a concentration with the specified student.
   * @summary Add a concentration to a student
   */
  const postStudentsIdConcentrations = (
    id: string,
    studentConcentrationPostInput: StudentConcentrationPostInput,
  ) => {
    return customAxios<void>({
      url: `/students/${id}/concentrations`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: studentConcentrationPostInput,
    });
  };
  /**
   * Removes the association between a student and a concentration.
   * @summary Remove a concentration from a student
   */
  const deleteStudentsIdConcentrationsConcentrationId = (id: string, concentrationId: number) => {
    return customAxios<void>({
      url: `/students/${id}/concentrations/${concentrationId}`,
      method: "DELETE",
    });
  };
  /**
   * Associates a minor with the specified student.
   * @summary Add a minor to a student
   */
  const postStudentsIdMinors = (id: string, studentMinorPostInput: StudentMinorPostInput) => {
    return customAxios<void>({
      url: `/students/${id}/minors`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: studentMinorPostInput,
    });
  };
  /**
   * Removes the association between a student and a minor.
   * @summary Remove a minor from a student
   */
  const deleteStudentsIdMinorsMinorId = (id: string, minorId: number) => {
    return customAxios<void>({ url: `/students/${id}/minors/${minorId}`, method: "DELETE" });
  };
  return {
    getStudents,
    postStudents,
    getStudentsEmailEmail,
    getStudentsId,
    patchStudentsId,
    deleteStudentsId,
    postStudentsIdMajors,
    deleteStudentsIdMajorsMajorId,
    postStudentsIdConcentrations,
    deleteStudentsIdConcentrationsConcentrationId,
    postStudentsIdMinors,
    deleteStudentsIdMinorsMinorId,
  };
};
export type GetStudentsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["getStudents"]>>
>;
export type PostStudentsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["postStudents"]>>
>;
export type GetStudentsEmailEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["getStudentsEmailEmail"]>>
>;
export type GetStudentsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["getStudentsId"]>>
>;
export type PatchStudentsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["patchStudentsId"]>>
>;
export type DeleteStudentsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["deleteStudentsId"]>>
>;
export type PostStudentsIdMajorsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["postStudentsIdMajors"]>>
>;
export type DeleteStudentsIdMajorsMajorIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["deleteStudentsIdMajorsMajorId"]>>
>;
export type PostStudentsIdConcentrationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["postStudentsIdConcentrations"]>>
>;
export type DeleteStudentsIdConcentrationsConcentrationIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getStudent>["deleteStudentsIdConcentrationsConcentrationId"]>
  >
>;
export type PostStudentsIdMinorsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["postStudentsIdMinors"]>>
>;
export type DeleteStudentsIdMinorsMinorIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStudent>["deleteStudentsIdMinorsMinorId"]>>
>;
