/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type {
  AcademicSemester,
  GetTraceOfferHistoryParams,
  GetTraceParams,
  Trace
} from './northStarAPI.schemas';

import { customAxios } from './apiClient';




  export const getTrace = () => {
/**
 * Retrieves a paginated list of TRACE data with optional filtering.
 * @summary Get all TRACE records
 */
const getTrace = (
    params?: GetTraceParams,
 ) => {
      return customAxios<Trace[]>(
      {url: `/trace`, method: 'GET',
        params
    },
      );
    }
  /**
 * Retrieves paginated list of offer-history.
 * @summary Get the Offer History offered by the TRACE Records
 */
const getTraceOfferHistory = (
    params?: GetTraceOfferHistoryParams,
 ) => {
      return customAxios<AcademicSemester[]>(
      {url: `/trace/offer-history`, method: 'GET',
        params
    },
      );
    }
  return {getTrace,getTraceOfferHistory}};
export type GetTraceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTrace>['getTrace']>>>
export type GetTraceOfferHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTrace>['getTraceOfferHistory']>>>
