/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import type { GetTraceParams, Trace } from "./northStarAPI.schemas";

import { customAxios } from "./apiClient";

export const getTrace = () => {
  /**
   * Retrieves a paginated list of TRACE data with optional filtering.
   * @summary Get all TRACE records
   */
  const getTrace = (params?: GetTraceParams) => {
    return customAxios<Trace[]>({ url: `/trace`, method: "GET", params });
  };
  return { getTrace };
};
export type GetTraceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTrace>["getTrace"]>>
>;
