/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * NorthStar API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type UuidParam = string;

/**
 * Error message or validation errors
 */
export type ErrorMessage = string | { [key: string]: unknown };

export interface Error {
  /** HTTP status code */
  code: number;
  /** Error message or validation errors */
  message: ErrorMessage;
}

export interface Favorite {
  student_id: string;
  course_id: string;
  created_at: string;
  updated_at: string;
}

export interface FavoriteCreate {
  student_id: string;
  course_id: string;
}

export interface FavoritesListResponse {
  items: Favorite[];
  /** @minimum 0 */
  total: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit: number;
  /** @minimum 0 */
  offset: number;
}

export interface Sample {
  /** The ID of the sample retrieved */
  id: string;
  /** The name of the sample */
  name: string;
  created_at: string;
  updated_at: string;
}

export interface SamplePostInput {
  /** @minLength 1 */
  name: string;
}

export interface SamplePatchInput {
  /** @minLength 1 */
  name?: string;
  updated_at?: string;
}

/**
 * The department offering the course
 */
export type CourseDepartment = {
  /** The ID of the department offering the course */
  id: number;
  /** The name of the department offering the course */
  name: string;
};

/**
 * The type of lecture format for the course
 */
export type CourseLectureType = typeof CourseLectureType[keyof typeof CourseLectureType] | null;


export const CourseLectureType = {
  lecture: 'lecture',
  lab: 'lab',
  online: 'online',
} as const;

export interface Course {
  /** The ID of the course retrieved */
  id: string;
  /** The name of the course */
  name: string;
  /** The department offering the course */
  department: CourseDepartment;
  /** The identifying code for the course within the department */
  course_code: number;
  /** A brief description of the course content and objectives */
  description: string;
  /** The number of credits awarded for completing the course */
  num_credits: number;
  /** The type of lecture format for the course */
  lecture_type?: CourseLectureType;
  created_at: string;
  updated_at: string;
}

/**
 * The type of lecture format for the course
 */
export type CoursePostInputLectureType = typeof CoursePostInputLectureType[keyof typeof CoursePostInputLectureType] | null;


export const CoursePostInputLectureType = {
  lecture: 'lecture',
  lab: 'lab',
  online: 'online',
} as const;

export interface CoursePostInput {
  /** The name of the course to be created */
  name: string;
  /** The ID of the department offering the course */
  department_id: number;
  /**
   * The identifying code for the course within the department
   * @minimum 1000
   * @maximum 10000
   */
  course_code: number;
  /** A brief description of the course content and objectives */
  description: string;
  /**
   * The number of credits awarded for completing the course
   * @minimum 1
   * @maximum 6
   */
  num_credits: number;
  /** The type of lecture format for the course */
  lecture_type?: CoursePostInputLectureType;
}

/**
 * The type of lecture format for the course
 */
export type CoursePatchInputLectureType = typeof CoursePatchInputLectureType[keyof typeof CoursePatchInputLectureType];


export const CoursePatchInputLectureType = {
  lecture: 'lecture',
  lab: 'lab',
  online: 'online',
} as const;

export interface CoursePatchInput {
  /** The name of the course to be created */
  name?: string;
  /** The ID of the department offering the course */
  department_id?: number;
  /**
   * The identifying code for the course within the department
   * @minimum 1000
   * @maximum 10000
   */
  course_code?: number;
  /** A brief description of the course content and objectives */
  description?: string;
  /**
   * The number of credits awarded for completing the course
   * @minimum 1
   * @maximum 6
   */
  num_credits?: number;
  /** The type of lecture format for the course */
  lecture_type?: CoursePatchInputLectureType;
}

export interface CourseThread {
  id: UuidParam;
  studentId: UuidParam;
  courseReviewId: UuidParam;
  /** @maxLength 2000 */
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface CourseThreadPostInput {
  studentId: UuidParam;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}

export interface CourseThreadPatchInput {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}

export type ProfessorTagsItem = typeof ProfessorTagsItem[keyof typeof ProfessorTagsItem];


export const ProfessorTagsItem = {
  boston: 'boston',
  oakland: 'oakland',
  london: 'london',
} as const;

export interface Professor {
  /** the unique id of the professor */
  id: string;
  /** the first name of the professor */
  firstName: string;
  /** the last name of the professor */
  lastName: string;
  /** location tags for the professor */
  tags?: ProfessorTagsItem[] | null;
  createdAt: string;
  updatedAt: string;
}

export type ProfessorPostInputTagsItem = typeof ProfessorPostInputTagsItem[keyof typeof ProfessorPostInputTagsItem];


export const ProfessorPostInputTagsItem = {
  boston: 'boston',
  oakland: 'oakland',
  london: 'london',
} as const;

export interface ProfessorPostInput {
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  tags?: ProfessorPostInputTagsItem[] | null;
}

export type ProfessorPatchInputTagsItem = typeof ProfessorPatchInputTagsItem[keyof typeof ProfessorPatchInputTagsItem];


export const ProfessorPatchInputTagsItem = {
  boston: 'boston',
  oakland: 'oakland',
  london: 'london',
} as const;

export interface ProfessorPatchInput {
  /** @minLength 1 */
  firstName?: string;
  /** @minLength 1 */
  lastName?: string;
  tags?: ProfessorPatchInputTagsItem[] | null;
}

export type BadRequestError = Error;

export type InternalServerError = Error & {
  /** The ID of the sample retrieved */
  id?: string;
  /** The name of the sample */
  name?: string;
  created_at?: string;
  updated_at?: string;
};

export type GetCourseReviewsIdThreadsParams = {
/**
 * Page number of pagination
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page in pagination
 * @minimum 1
 */
limit?: number;
};

export type GetSamplesParams = {
/**
 * Page number of pagination
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page in pagination
 * @minimum 1
 */
limit?: number;
};

export type GetCoursesParams = {
/**
 * Page number of pagination
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page in pagination
 * @minimum 1
 */
limit?: number;
};

export type GetProfessorsParams = {
/**
 * Page number of pagination
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page in pagination
 * @minimum 1
 */
limit?: number;
};

export type GetFavoritesParams = {
/**
 * Maximum number of items to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Number of items to skip
 * @minimum 0
 */
offset?: number;
};

export const getNorthStarAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * Check if the API is running and healthy.
 * @summary Health check
 */
const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

/**
 * Returns all thread messages associated with a single course review (identified by the course review UUID).
This is used to display the discussion/comments under a course review in the UI.

 * @summary List threads for a course review
 */
const getCourseReviewsIdThreads = (
    id: UuidParam,
    params?: GetCourseReviewsIdThreadsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseThread[]>> => {
    return axiosInstance.get(
      `/course-reviews/${id}/threads`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Creates a new thread message under a specific course review.
The course review ID comes from the path, and the request body provides the studentId and message content.

 * @summary Create a thread on a course review
 */
const postCourseReviewsIdThreads = (
    id: UuidParam,
    courseThreadPostInput: CourseThreadPostInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseThread>> => {
    return axiosInstance.post(
      `/course-reviews/${id}/threads`,
      courseThreadPostInput,options
    );
  }

/**
 * Updates an existing thread message under a course review.
The course review ID and thread ID are provided in the path; the request body includes the updated content.

 * @summary Update a thread
 */
const patchCourseReviewsCourseReviewIdThreadsThreadId = (
    courseReviewId: UuidParam,
    threadId: UuidParam,
    courseThreadPatchInput: CourseThreadPatchInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseThread>> => {
    return axiosInstance.patch(
      `/course-reviews/${courseReviewId}/threads/${threadId}`,
      courseThreadPatchInput,options
    );
  }

/**
 * Deletes a thread message under a course review.
The course review ID and thread ID are provided in the path.

 * @summary Delete a thread
 */
const deleteCourseReviewsCourseReviewIdThreadsThreadId = (
    courseReviewId: UuidParam,
    threadId: UuidParam, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/course-reviews/${courseReviewId}/threads/${threadId}`,options
    );
  }

/**
 * This endpoint gets all samples that we have
 * @summary Getting Samples
 */
const getSamples = (
    params?: GetSamplesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample[]>> => {
    return axiosInstance.get(
      `/samples`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * This endpoint creates a new sample with the provided details
 * @summary Create a New Sample
 */
const postSamples = (
    samplePostInput: SamplePostInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample>> => {
    return axiosInstance.post(
      `/samples`,
      samplePostInput,options
    );
  }

/**
 * This endpoint retrieves a specific sample by its ID
 * @summary Get Sample by ID
 */
const getSamplesId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample>> => {
    return axiosInstance.get(
      `/samples/${id}`,options
    );
  }

/**
 * This endpoint updates the details of a specific sample by its ID
 * @summary Update Sample by ID
 */
const patchSamplesId = (
    id: string,
    samplePatchInput: SamplePatchInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample>> => {
    return axiosInstance.patch(
      `/samples/${id}`,
      samplePatchInput,options
    );
  }

/**
 * This endpoint deletes a specific sample by its ID
 * @summary Delete Sample by ID
 */
const deleteSamplesId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/samples/${id}`,options
    );
  }

/**
 * This endpoint retrieves all available courses as a list
 * @summary Getting All Courses
 */
const getCourses = (
    params?: GetCoursesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course[]>> => {
    return axiosInstance.get(
      `/courses`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * This endpoint creates a new course with the provided details
 * @summary Create a New Course
 */
const postCourses = (
    coursePostInput: CoursePostInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course>> => {
    return axiosInstance.post(
      `/courses`,
      coursePostInput,options
    );
  }

/**
 * This endpoint retrieves a specific course by its ID
 * @summary Get Course by ID
 */
const getCoursesId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course>> => {
    return axiosInstance.get(
      `/courses/${id}`,options
    );
  }

/**
 * This endpoint updates the details of a specific course by its ID
 * @summary Update Course by ID
 */
const patchCoursesId = (
    id: string,
    coursePatchInput: CoursePatchInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Course>> => {
    return axiosInstance.patch(
      `/courses/${id}`,
      coursePatchInput,options
    );
  }

/**
 * This endpoint deletes a specific course by its ID
 * @summary Delete Course by ID
 */
const deleteCoursesId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/courses/${id}`,options
    );
  }

/**
 * Returns a list of all professors
 * @summary Get all professors
 */
const getProfessors = (
    params?: GetProfessorsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Professor[]>> => {
    return axiosInstance.get(
      `/professors`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Creates a new professor
 * @summary Create a professor
 */
const postProfessors = (
    professorPostInput: ProfessorPostInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Professor>> => {
    return axiosInstance.post(
      `/professors`,
      professorPostInput,options
    );
  }

/**
 * Returns a single professor by their UUID
 * @summary Get professor by ID
 */
const getProfessorsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Professor>> => {
    return axiosInstance.get(
      `/professors/${id}`,options
    );
  }

/**
 * Partially updates a professor by their UUID
 * @summary Update a professor
 */
const patchProfessorsId = (
    id: string,
    professorPatchInput: ProfessorPatchInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Professor>> => {
    return axiosInstance.patch(
      `/professors/${id}`,
      professorPatchInput,options
    );
  }

/**
 * Deletes a professor by their UUID
 * @summary Delete a professor
 */
const deleteProfessorsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/professors/${id}`,options
    );
  }

/**
 * Returns a paginated list of favorites
 * @summary List favorites
 */
const getFavorites = (
    params?: GetFavoritesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FavoritesListResponse>> => {
    return axiosInstance.get(
      `/favorites`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Create a new favorite
 * @summary Create favorite
 */
const postFavorites = (
    favoriteCreate: FavoriteCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Favorite>> => {
    return axiosInstance.post(
      `/favorites`,
      favoriteCreate,options
    );
  }

/**
 * Delete favorite by student_id and course_id
 * @summary Delete favorite
 */
const deleteFavoritesStudentIdCourseId = (
    studentId: string,
    courseId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/favorites/${studentId}/${courseId}`,options
    );
  }

return {getHealth,getCourseReviewsIdThreads,postCourseReviewsIdThreads,patchCourseReviewsCourseReviewIdThreadsThreadId,deleteCourseReviewsCourseReviewIdThreadsThreadId,getSamples,postSamples,getSamplesId,patchSamplesId,deleteSamplesId,getCourses,postCourses,getCoursesId,patchCoursesId,deleteCoursesId,getProfessors,postProfessors,getProfessorsId,patchProfessorsId,deleteProfessorsId,getFavorites,postFavorites,deleteFavoritesStudentIdCourseId}};
export type GetHealthResult = AxiosResponse<void>
export type GetCourseReviewsIdThreadsResult = AxiosResponse<CourseThread[]>
export type PostCourseReviewsIdThreadsResult = AxiosResponse<CourseThread>
export type PatchCourseReviewsCourseReviewIdThreadsThreadIdResult = AxiosResponse<CourseThread>
export type DeleteCourseReviewsCourseReviewIdThreadsThreadIdResult = AxiosResponse<void>
export type GetSamplesResult = AxiosResponse<Sample[]>
export type PostSamplesResult = AxiosResponse<Sample>
export type GetSamplesIdResult = AxiosResponse<Sample>
export type PatchSamplesIdResult = AxiosResponse<Sample>
export type DeleteSamplesIdResult = AxiosResponse<void>
export type GetCoursesResult = AxiosResponse<Course[]>
export type PostCoursesResult = AxiosResponse<Course>
export type GetCoursesIdResult = AxiosResponse<Course>
export type PatchCoursesIdResult = AxiosResponse<Course>
export type DeleteCoursesIdResult = AxiosResponse<void>
export type GetProfessorsResult = AxiosResponse<Professor[]>
export type PostProfessorsResult = AxiosResponse<Professor>
export type GetProfessorsIdResult = AxiosResponse<Professor>
export type PatchProfessorsIdResult = AxiosResponse<Professor>
export type DeleteProfessorsIdResult = AxiosResponse<void>
export type GetFavoritesResult = AxiosResponse<FavoritesListResponse>
export type PostFavoritesResult = AxiosResponse<Favorite>
export type DeleteFavoritesStudentIdCourseIdResult = AxiosResponse<void>
