import { pgEnum} from "drizzle-orm/pg-core";
import { professor } from "./professor";

export const professorTagEnum = pgEnum("professor_tag_enum", [
    "clear_lectures",
    "confusing_lectures",
    "organized",
    "disorganized",
    "engaging",
    "boring",
    "reads_slides",
    "fair_grading",
    "tough_grader",
    "lenient_grader",
    "unclear_rubrics",
    "curve_based",
    "no_curve",
    "tricky_exams",
    "straightforward_exams",
    "heavy_workload",
    "manageable_workload",
    "busywork",
    "high_expectations",
    "low_expectations",
    "approachable",
    "unapproachable",
    "responsive",
    "slow_responder",
    "caring",
    "intimidating",
    "passionate",
    "monotone",
    "attendance_required",
    "attendance_optional",
    "strict_deadlines",
    "flexible_deadlines",
    "extra_credit",
    "no_extra_credit",
    "little_to_no_test",
]);